#!/usr/bin/env bash
# {{ansible_managed}}
set -ex

ANSIBLE_VARARGS=""
if [ -e /setup/reconfigure.yml ];then
    ANSIBLE_VARARGS="-e @/setup/reconfigure.yml"
fi
# Reconfigure (extra-light reprovision) app from user volumes/env
if [[ -z ${NO_CONFIG-} ]];then
    cd /provision_dir
    /srv/corpusops/corpusops.bootstrap/bin/cops_apply_role \
        $ANSIBLE_VARARGS \
        -vvvv {{ep_playbook}} \
        --tags={{ep_tags}} \
        --skip-tags={{ep_skip_tags}}
fi

# Launch app (via systemd)
cd /
if [[ -n ${USE_INIT-} ]];then
    exec {{ep_main_ep}}
else
    if [[ -z ${NO_RESTART-} ]];then
{% for i in ep_services %}
        systemctl restart {{i}}
{% endfor %}
    fi
fi
